---
- name: create Amazon Web Services
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - ec2
  tasks:
    - name: Refresh inventory
      meta: refresh_inventory

- name: build Google Chrome
  hosts: tag_Name_HeadlessChrome
  user: ec2-user
  become: True
  gather_facts: true
  roles:
    - zypper
    - pip
    - chrome
