---
- name: Unarchive a chromedriver that needs to be downloaded
  unarchive:
    src: '{{ chromedriver_url }}'
    dest: '{{ chromedriver_path }}'
    remote_src: yes

- name: Copy sample-script to use it for operation check
  copy:
    src: '{{ sample_script.name }}'
    dest: '{{ sample_script.path }}'
