---
aws:
  common:
    region: ap-northeast-1
  vpc:
    name: AnsibleVPC
    cidr_block: 10.0.0.0/16
    tags:
      Name: AnsibleVPC
    igw:
      tags:
        Name: AnsibleIGW
    subnet:
      subnet1:
        tags:
          Name: public-a
          route: public
        cidr: 10.0.1.0/24
        zone: a
    route_table:
      tags:
        Name: public-route-table
    security_group:
      security_group1:
        name: AnsibleSSH
        description: EC2 group
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
    ec2:
      name: HeadlessChrome
      instance_type: t2.micro
      image: ami-adc974cb
